name: Deploy Symfony API with MySQL and Nginx

on:
    push:
        branches:
            - despliegueDocker

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Iniciar sesión en Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Construir y subir imagen Symfony + Nginx
            - name: Construir y subir imagen Symfony + Nginx
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/symfony-app:${{ github.sha }} -f backend/EdelmiroMonros/docker/php.Dockerfile backend/EdelmiroMonros/
                  docker push ${{ secrets.DOCKER_USERNAME }}/symfony-app:${{ github.sha }}

    deploy:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            - name: Checkout código
              uses: actions/checkout@v4
              with:
                  ref: despliegueDocker # Asegura que se usa esta rama

            - name: Verificar estructura del repositorio
              run: |
                  echo "Directorio actual: $(pwd)"
                  ls -R

            - name: Transferir el archivo compose.yml al servidor remoto
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_KEY }}
                  source: ./backend/EdelmiroMonros/compose.yml
                  target: ~/deploy/

            - name: Desplegar en servidor remoto
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_KEY }}
                  script: |
                      docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

                      docker pull ${{ secrets.DOCKER_USERNAME }}/symfony-app:${{ github.sha }}

                      docker-compose -f /home/${{ secrets.REMOTE_USER }}/deploy/compose.yml down
                      docker-compose -f /home/${{ secrets.REMOTE_USER }}/deploy/compose.yml up -d --force-recreate

                      docker exec symfony_php php bin/console doctrine:migrations:migrate --no-interaction
